version: "3"

services:
  db:
    image: mysql:8.0.32
    env_file:
      - ../.env.db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306" # 배포 전 삭제할 것

  backend:
    env_file:
      - ../.env.backend
    build:
      context: ..
      dockerfile: .devcontainer/backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    volumes:
      - ../backend:/app # 개발 끝나고 지울 것

  frontend:
    env_file:
      - ../.env.frontend
    build:
      context: ..
      dockerfile: .devcontainer/frontend/Dockerfile
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"

volumes:
  db-data:
